# Generated by Django 3.2.6 on 2021-11-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0002_auto_20211118_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_data',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agric.location'),
        ),
        migrations.AlterField(
            model_name='bio_data',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agric.marital_status'),
        ),
        migrations.AlterField(
            model_name='bio_data',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agric.sex'),
        ),
    ]
