# Generated by Django 3.2.6 on 2021-11-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0003_auto_20211118_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_data',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbio_data',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
