# Generated by Django 3.2.6 on 2021-11-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0004_auto_20211118_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='value_chain',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='bio_data',
            name='value_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agric.value_chain'),
        ),
    ]
