# Generated by Django 3.2.6 on 2021-11-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0009_auto_20211119_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop_farming',
            old_name='yields',
            new_name='current_yields',
        ),
        migrations.RenameField(
            model_name='historicalcrop_farming',
            old_name='yields',
            new_name='current_yields',
        ),
    ]
