# Generated by Django 3.2.6 on 2021-11-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0010_auto_20211119_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animals',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='crops',
            options={'ordering': ('name',)},
        ),
    ]
