# Generated by Django 3.2.6 on 2021-11-19 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0012_animalfarming_yeild_historicalanimalfarming_yeild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associations',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agric.value_chain'),
        ),
        migrations.AlterField(
            model_name='historicalassociations',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agric.value_chain'),
        ),
    ]
