# Generated by Django 3.2.6 on 2021-11-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0013_auto_20211119_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associations',
            old_name='type',
            new_name='value_chain',
        ),
        migrations.RenameField(
            model_name='historicalassociations',
            old_name='type',
            new_name='value_chain',
        ),
    ]
