# Generated by Django 3.2.6 on 2021-11-20 20:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agric', '0015_auto_20211119_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_info',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='historicalbusiness_info',
            name='bio',
        ),
        migrations.AddField(
            model_name='business_info',
            name='scale',
            field=models.CharField(choices=[('Small Scale', 'Small Scale'), ('Medium Scale', 'Medium Scale')], default=datetime.datetime(2021, 11, 20, 19, 59, 29, 837815, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business_info',
            name='type_ownership',
            field=models.CharField(choices=[('Single Ownership', 'Single Ownership'), ('Multi Ownership', 'Multi Ownership')], default=datetime.datetime(2021, 11, 20, 19, 59, 50, 259378, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbusiness_info',
            name='scale',
            field=models.CharField(choices=[('Small Scale', 'Small Scale'), ('Medium Scale', 'Medium Scale')], default=datetime.datetime(2021, 11, 20, 20, 0, 12, 168346, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbusiness_info',
            name='type_ownership',
            field=models.CharField(choices=[('Single Ownership', 'Single Ownership'), ('Multi Ownership', 'Multi Ownership')], default=datetime.datetime(2021, 11, 20, 20, 0, 32, 653228, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoricalBio_business',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agric.bio_data')),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agric.animals')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bio_business',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Bio_business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agric.bio_data')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agric.animals')),
            ],
        ),
    ]
