# Generated by Django 3.2.6 on 2021-11-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0016_auto_20211120_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_info',
            name='permit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbusiness_info',
            name='permit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
