# Generated by Django 3.2.6 on 2021-11-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0017_auto_20211120_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_info',
            name='casual_staff_no',
        ),
        migrations.RemoveField(
            model_name='historicalbusiness_info',
            name='casual_staff_no',
        ),
    ]
