# Generated by Django 3.2.6 on 2021-11-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0018_auto_20211120_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_info',
            name='other',
        ),
        migrations.RemoveField(
            model_name='historicalbusiness_info',
            name='other',
        ),
        migrations.AddField(
            model_name='business_info',
            name='casual_staff_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalbusiness_info',
            name='casual_staff_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='HistoricalOther',
        ),
        migrations.DeleteModel(
            name='Other',
        ),
    ]
