# Generated by Django 3.2.6 on 2021-11-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0019_auto_20211120_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_business',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agric.business_info'),
        ),
        migrations.AlterField(
            model_name='historicalbio_business',
            name='business',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agric.business_info'),
        ),
    ]
