# Generated by Django 3.2.6 on 2021-11-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0020_auto_20211120_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_info',
            name='scale',
            field=models.CharField(choices=[('Small Scale', 'Small Scale'), ('Medium Scale', 'Medium Scale'), ('Large Scale', 'Large Scale')], max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalbusiness_info',
            name='scale',
            field=models.CharField(choices=[('Small Scale', 'Small Scale'), ('Medium Scale', 'Medium Scale'), ('Large Scale', 'Large Scale')], max_length=255),
        ),
    ]
