# Generated by Django 3.2.6 on 2021-11-21 09:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agric', '0021_auto_20211120_2214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bio_business',
            new_name='Business_Partners',
        ),
        migrations.RenameModel(
            old_name='HistoricalBio_business',
            new_name='HistoricalBusiness_Partners',
        ),
        migrations.AlterModelOptions(
            name='historicalbusiness_partners',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical business_ partners'},
        ),
        migrations.AddField(
            model_name='business_info',
            name='bio',
            field=models.ForeignKey(default=datetime.datetime(2021, 11, 21, 9, 57, 36, 529610, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='agric.bio_data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbusiness_info',
            name='bio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agric.bio_data'),
        ),
    ]
