# Generated by Django 3.2.6 on 2021-11-21 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0022_auto_20211121_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_info',
            name='bio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agric.bio_data'),
        ),
    ]
