# Generated by Django 3.2.6 on 2021-11-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0024_auto_20211122_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio_data',
            name='type',
            field=models.CharField(choices=[('Agric-Base', 'Agric-Base'), ('Others', 'Others')], default='Agric-Base', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalbio_data',
            name='type',
            field=models.CharField(choices=[('Agric-Base', 'Agric-Base'), ('Others', 'Others')], default='Agric-Base', max_length=30),
        ),
    ]
