# Generated by Django 3.2.6 on 2021-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0025_auto_20211122_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='land',
            name='business',
        ),
        migrations.RemoveField(
            model_name='bio_data',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicalbio_data',
            name='type',
        ),
        migrations.AddField(
            model_name='business_info',
            name='land_title_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Unregistered', 'Unregistered')], default='Registered', max_length=255),
        ),
        migrations.AddField(
            model_name='business_info',
            name='total_area_under_cultivation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business_info',
            name='total_land_area_of_farm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalbusiness_info',
            name='land_title_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Unregistered', 'Unregistered')], default='Registered', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbusiness_info',
            name='total_area_under_cultivation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalbusiness_info',
            name='total_land_area_of_farm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='HistoricalLand',
        ),
        migrations.DeleteModel(
            name='Land',
        ),
    ]
