# Generated by Django 3.2.6 on 2021-12-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0026_auto_20211209_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_data',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agric.marital_status'),
        ),
    ]
