# Generated by Django 3.2.6 on 2021-12-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0027_alter_bio_data_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_info',
            name='led_by_woman',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AddField(
            model_name='business_info',
            name='owned_by_woman',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbusiness_info',
            name='led_by_woman',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalbusiness_info',
            name='owned_by_woman',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
    ]
