# Generated by Django 3.2.6 on 2021-12-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0028_auto_20211209_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_info',
            name='type_ownership',
            field=models.CharField(choices=[('Single Ownership', 'Single Ownership'), ('Multi Ownership', 'Multi Ownership')], default='Single Ownership', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalbusiness_info',
            name='type_ownership',
            field=models.CharField(choices=[('Single Ownership', 'Single Ownership'), ('Multi Ownership', 'Multi Ownership')], default='Single Ownership', max_length=255),
        ),
    ]
