# Generated by Django 3.2.6 on 2021-12-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0029_auto_20211209_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_info',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='business_info',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='historicalbusiness_info',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='historicalbusiness_info',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
    ]
