# Generated by Django 3.2.6 on 2021-12-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0031_auto_20211209_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalfarming_yeild',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='animalfarming_yeild',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalanimalfarming_yeild',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='historicalanimalfarming_yeild',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
