# Generated by Django 3.2.6 on 2021-12-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0034_auto_20211209_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropfarming_yeild',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='cropfarming_yeild',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='historicalcropfarming_yeild',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='historicalcropfarming_yeild',
            name='longitude',
        ),
        migrations.AddField(
            model_name='crop_farming',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='crop_farming',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrop_farming',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrop_farming',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
