# Generated by Django 3.2.6 on 2021-12-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agric', '0035_auto_20211209_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_info',
            name='owned_by_woman',
        ),
        migrations.RemoveField(
            model_name='historicalbusiness_info',
            name='owned_by_woman',
        ),
    ]
